import type { DashboardState } from '@/types'

export const MOCK_STATE: DashboardState = {
  agents: [
    {
      id: 'lead',
      role: 'Orchestrator (main session)',
      modelTier: 'opus',
      status: 'working',
      color: 'blue',
      ticketsAssigned: 0,
      ticketsCompleted: 0,
      currentTicket: null,
      sessionId: 'main',
    },
    {
      id: 'takt-data-engineer',
      role: 'Dataset loading and parsing',
      modelTier: 'sonnet',
      status: 'working',
      color: 'blue',
      ticketsAssigned: 4,
      ticketsCompleted: 2,
      currentTicket: 'T007',
      sessionId: 'a4172b2c-5814-48f0-b1a2-9e3f4d5c6a7b',
    },
    {
      id: 'takt-eval-engineer',
      role: 'Evaluation pipeline',
      modelTier: 'opus',
      status: 'idle',
      color: 'red',
      ticketsAssigned: 5,
      ticketsCompleted: 3,
      currentTicket: null,
      sessionId: 'a56155f2-6467-4554-b1f6-0b285ee3eea6',
    },
    {
      id: 'takt-test-engineer',
      role: 'Testing specialist',
      modelTier: 'sonnet',
      status: 'working',
      color: 'green',
      ticketsAssigned: 6,
      ticketsCompleted: 4,
      currentTicket: 'T015',
      sessionId: 'bf5cc789-cffa-4f62-8685-7dbbb40f56da',
    },
    {
      id: 'takt-ml-scientist',
      role: 'Architecture survey and SOTA benchmarks',
      modelTier: 'opus',
      status: 'completed',
      color: 'yellow',
      ticketsAssigned: 3,
      ticketsCompleted: 3,
      currentTicket: null,
      sessionId: 'fb3350fb-1fc2-4403-b2a1-c9d8e7f6a5b4',
    },
    {
      id: 'takt-speech-scientist',
      role: 'Dataset survey and G2P tools',
      modelTier: 'sonnet',
      status: 'idle',
      color: 'purple',
      ticketsAssigned: 2,
      ticketsCompleted: 2,
      currentTicket: null,
      sessionId: 'feb08f4c-1a31-4655-9c8d-2e3f4a5b6c7d',
    },
    {
      id: 'takt-phonetician',
      role: 'IPA inventories and cross-language phonology',
      modelTier: 'opus',
      status: 'idle',
      color: 'cyan',
      ticketsAssigned: 3,
      ticketsCompleted: 1,
      currentTicket: null,
      sessionId: null,
    },
  ],
  tickets: [
    { id: 'T001', title: 'Shared Data Models', agentId: 'takt-data-engineer', milestone: 'Foundation', status: 'completed', priority: 'critical', dependencies: [] },
    { id: 'T002', title: 'Eval Config', agentId: 'takt-eval-engineer', milestone: 'Foundation', status: 'completed', priority: 'high', dependencies: [] },
    { id: 'T003', title: 'YAML Configs', agentId: 'takt-eval-engineer', milestone: 'Foundation', status: 'completed', priority: 'medium', dependencies: ['T001'] },
    { id: 'T007', title: 'L2-ARCTIC Loader', agentId: 'takt-data-engineer', milestone: 'Data Loaders', status: 'in-progress', priority: 'critical', dependencies: ['T001'] },
    { id: 'T008', title: 'SpeechOcean Loader', agentId: 'takt-data-engineer', milestone: 'Data Loaders', status: 'pending', priority: 'high', dependencies: ['T001'] },
    { id: 'T015', title: 'Integration Tests', agentId: 'takt-test-engineer', milestone: 'Metrics Engine', status: 'in-progress', priority: 'high', dependencies: ['T007'] },
    { id: 'T020', title: 'Inference Runner', agentId: 'takt-eval-engineer', milestone: 'Inference', status: 'pending', priority: 'critical', dependencies: ['T007', 'T008'] },
  ],
  activity: [
    { timestamp: '2026-02-12T17:32:09.000Z', agentId: 'takt-data-engineer', sessionId: 'a4172b2c-5814-48f0-b1a2-9e3f4d5c6a7b', type: 'ticket-started', summary: '[takt-data-engineer] Started T007: L2-ARCTIC Loader' },
    { timestamp: '2026-02-12T17:30:45.000Z', agentId: 'takt-test-engineer', sessionId: 'bf5cc789-cffa-4f62-8685-7dbbb40f56da', type: 'ticket-started', summary: '[takt-test-engineer] Started T015: Integration Tests' },
    { timestamp: '2026-02-12T17:28:12.000Z', agentId: 'takt-eval-engineer', sessionId: 'a56155f2-6467-4554-b1f6-0b285ee3eea6', type: 'ticket-completed', summary: '[takt-eval-engineer] Completed T003: YAML Configs' },
    { timestamp: '2026-02-12T17:24:57.000Z', agentId: 'takt-eval-engineer', sessionId: 'a56155f2-6467-4554-b1f6-0b285ee3eea6', type: 'agent-idle', summary: '[takt-eval-engineer] Waiting for dependencies' },
    { timestamp: '2026-02-12T17:22:39.000Z', agentId: 'takt-ml-scientist', sessionId: 'fb3350fb-1fc2-4403-b2a1-c9d8e7f6a5b4', type: 'ticket-completed', summary: '[takt-ml-scientist] Completed all assigned tickets' },
    { timestamp: '2026-02-12T17:20:00.000Z', agentId: null, sessionId: null, type: 'milestone-completed', summary: 'Milestone M001 (Foundation) completed' },
    { timestamp: '2026-02-12T17:15:33.000Z', agentId: 'takt-data-engineer', sessionId: 'a4172b2c-5814-48f0-b1a2-9e3f4d5c6a7b', type: 'ticket-completed', summary: '[takt-data-engineer] Completed T001: Shared Data Models' },
    { timestamp: '2026-02-12T17:10:00.000Z', agentId: null, sessionId: null, type: 'system', summary: 'Takt session started: pronunciation-eval' },
  ],
  project: {
    name: 'pronunciation-eval',
    phase: 'executing',
    status: 'executing',
    currentMilestone: 'M002',
    activeAgents: ['takt-data-engineer', 'takt-test-engineer'],
    ticketsSummary: {
      total: 26,
      completed: 12,
      inProgress: 2,
      pending: 10,
      blocked: 2,
      failed: 0,
    },
    startedAt: '2026-02-12T17:00:00.000Z',
    lastUpdatedAt: '2026-02-12T17:32:09.000Z',
  },
  resources: {
    daily: { used: 472_000, limit: 5_000_000, resetIn: '23h 18m' },
    weekly: { used: 472_000, limit: 20_000_000, resetIn: '3d 23h' },
    contextWindow: { used: 43_000, total: 200_000, percentage: 22 },
    model: 'claude-opus-4-5',
    lastUpdated: '2026-02-12T17:41:38.000Z',
  },
  messages: [
    { timestamp: '2026-02-12T17:25:00.000Z', from: 'takt-data-engineer', to: 'takt-eval-engineer', ticketId: 'T001', content: 'Data models ready for review', urgency: 'normal' },
    { timestamp: '2026-02-12T17:28:00.000Z', from: 'takt-eval-engineer', to: 'takt-data-engineer', ticketId: 'T007', content: 'Please ensure loader returns UtteranceRecord tuples', urgency: 'high' },
  ],
  error: null,
}
